name: Deploy to Firebase Hosting on new release
on:
  release:
    types: [published]

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@master
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TEAM_NEWS_3F573 }}"
          projectId: team-news-3f573
